### ISSUE TITLE
Introduction of daily trade in limit

### ISSUE THREAD

**Issue by FelOtt** [YimMenu-Lua/Casino-Pacino#14]
Rockstar added a trade in limit of 10.000.000$ per day to the casino. Are there any plans on removing that cooldown also?

**Comment by SpiffierDog6854** [comment]
how do i use the scrip

**Comment by FelOtt** [comment]
@SpiffierDog6854 either you create your own ticket, or you don't get an answer

**Comment by gir489returns** [comment]
> Rockstar added a trade in limit of 10.000.000$ per day to the casino. Are there any plans on removing that cooldown also?

Are you sure it's not just the Casino Cooldown reader that's already in there? Do you have more information about this 10,000,000 limit and how it's determined?

**Comment by FelOtt** [comment]
> > Rockstar added a trade in limit of 10.000.000$ per day to the casino. Are there any plans on removing that cooldown also?
> 
> Are you sure it's not just the Casino Cooldown reader that's already in there? Do you have more information about this 10,000,000 limit and how it's determined?

The trade in limit is pretty similar to the daily limit to buy tokens of 50.000. This has been in the game for years because of online gambling laws. Now the did the same thing for cashing out, this is probably to prevent hackers from making too much money from this. But principle is the same: When you're at the cashier it asks you, what you want to do - cash in or cash out. In the past you could cash ous as much as you wanted (I think, my max was 130m) but now it's capped at 10m

**Comment by gir489returns** [comment]
> The trade in limit is pretty similar to the daily limit to buy tokens of 50.000. This has been in the game for years because of online gambling laws. Now the did the same thing for cashing out, this is probably to prevent hackers from making too much money from this. But principle is the same: When you're at the cashier it asks you, what you want to do - cash in or cash out. In the past you could cash ous as much as you wanted (I think, my max was 130m) but now it's capped at 10m

It's 100% not because of online gambling laws, GTA V will not allow you to gamble at all if your country does not allow online gambling, there's a native we hook to bypass that called NETWORK::NETWORK_CASINO_CAN_BET. It takes a JOAAT hash of the game you're trying to play then returns either true or false. It was discovered very early that the IP you were using to connect to the social club API was the one used to determine if you could gamble, so VPNs became a popular solution to bypassing it until YimMenu came around. However, there are very few countries that still ban online gambling.

Anyway, what you're referring to is the tunable VC_CASINO_CHIP_MAX_WIN_DAILY. I didn't know you meant per game day, not real day. That's been in since the casinos were introduced, you worded your post as if they introduced this with 1.69. There's a Clear Cooldown button on Casino Pacino, but I do not recommend using it at all.

**Comment by FelOtt** [comment]
I checked and the cooldown bypass doesnt work. And YES, I have the current version...
Also here is a showcase: https://youtu.be/sr6Qa9Nj7-w

**Comment by FelOtt** [comment]
I checked and the cooldown bypass doesnt work. And YES, I have the current version...
Also here is a showcase: https://youtu.be/A54o65CZNLk

**Comment by gir489returns** [comment]
This is the trade-in limit, which Casino Pacino doesn't support.

**Comment by FelOtt** [comment]
Okay, firstly a big WOW!! I don't think you can read, because I clearly explained what the problem was in the first post in this ticket. I even used the same name that you did later (trade in limit), and I wasn't complaining about the script not working, but asking, if there are plans on supporting this in the future.
