### ISSUE TITLE
roulette not forcing?

### ISSUE THREAD

**Issue by faxiklas** [YimMenu-Lua/Casino-Pacino#4]
is the roulette setting being fixed? just asking 

not working

**Comment by TwystedMind** [comment]
Just curious if you're still experiencing this issue?  I've been using the most current version of this LUA, and have had no issues directly related to the script when rigging Roulette.  It appears to be working perfectly on both the regular floor tables as well as the "High Limit" tables.

The _only_ time I seem to ever experience an issue is when another player enters the casino and rigs the Roulette tables using their menu at the same time.  In those instances, Roulette seems to land on "00" every time.  I'm not sure if that is due to the other player's menu overriding the CasinoPacino script and their menu being set to intentionally land on "00", or if it is due to an interference between the two script takeovers.

Either way, I do not consider that an issue with this script directly, as it works perfect otherwise.  The only time I experienced CasinoPacino not working properly (would only control the normal Roulette tables), was when I mistakenly loaded an older version.

**Comment by faxiklas** [comment]
still not working dont know why cuz im using up to date yimmenu with or w/o lua's (except pacino) doesnt matter

tried to debug it but i have no idea how to debug anything :(

**Comment by faxiklas** [comment]
> Just curious if you're still experiencing this issue? I've been using the most current version of this LUA, and have had no issues directly related to the script when rigging Roulette. It appears to be working perfectly on both the regular floor tables as well as the "High Limit" tables.
> 
> The _only_ time I seem to ever experience an issue is when another player enters the casino and rigs the Roulette tables using their menu at the same time. In those instances, Roulette seems to land on "00" every time. I'm not sure if that is due to the other player's menu overriding the CasinoPacino script and their menu being set to intentionally land on "00", or if it is due to an interference between the two script takeovers.
> 
> Either way, I do not consider that an issue with this script directly, as it works perfect otherwise. The only time I experienced CasinoPacino not working properly (would only control the normal Roulette tables), was when I mistakenly loaded an older version.



still not working dont know why cuz im using up to date yimmenu with or w/o lua's (except pacino) doesnt matter

tried to debug it but i have no idea how to debug anything :(
